// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateMediaExceptionData, CreateMediaExceptionErrors, CreateMediaExceptionResponses, DeleteMediaExceptionData, DeleteMediaExceptionErrors, DeleteMediaExceptionResponses, GetByMediaKeyData, GetByMediaKeyErrors, GetByMediaKeyResponses, GetDefaultValuesData, GetDefaultValuesErrors, GetDefaultValuesResponses, UpdateMediaExceptionData, UpdateMediaExceptionErrors, UpdateMediaExceptionResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export class PageSpeedOptimizer {
    public static createMediaException<ThrowOnError extends boolean = false>(options?: Options<CreateMediaExceptionData, ThrowOnError>): RequestResult<CreateMediaExceptionResponses, CreateMediaExceptionErrors, ThrowOnError> {
        return (options?.client ?? client).post<CreateMediaExceptionResponses, CreateMediaExceptionErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/pagespeed-optimizer/v1/media-exception',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static deleteMediaException<ThrowOnError extends boolean = false>(options: Options<DeleteMediaExceptionData, ThrowOnError>): RequestResult<DeleteMediaExceptionResponses, DeleteMediaExceptionErrors, ThrowOnError> {
        return (options.client ?? client).delete<DeleteMediaExceptionResponses, DeleteMediaExceptionErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/pagespeed-optimizer/v1/media-exception/{id}',
            ...options
        });
    }
    
    public static updateMediaException<ThrowOnError extends boolean = false>(options: Options<UpdateMediaExceptionData, ThrowOnError>): RequestResult<UpdateMediaExceptionResponses, UpdateMediaExceptionErrors, ThrowOnError> {
        return (options.client ?? client).put<UpdateMediaExceptionResponses, UpdateMediaExceptionErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/pagespeed-optimizer/v1/media-exception/{id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    public static getByMediaKey<ThrowOnError extends boolean = false>(options: Options<GetByMediaKeyData, ThrowOnError>): RequestResult<GetByMediaKeyResponses, GetByMediaKeyErrors, ThrowOnError> {
        return (options.client ?? client).get<GetByMediaKeyResponses, GetByMediaKeyErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/pagespeed-optimizer/v1/media-exception/by-media-key/{mediaKey}',
            ...options
        });
    }
    
    public static getDefaultValues<ThrowOnError extends boolean = false>(options?: Options<GetDefaultValuesData, ThrowOnError>): RequestResult<GetDefaultValuesResponses, GetDefaultValuesErrors, ThrowOnError> {
        return (options?.client ?? client).get<GetDefaultValuesResponses, GetDefaultValuesErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/pagespeed-optimizer/v1/media-exception/default-values',
            ...options
        });
    }
}
