// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteMediaExceptionByIdData, DeleteMediaExceptionByIdErrors, DeleteMediaExceptionByIdResponses, GetMediaExceptionByMediaKeyByMediaKeyData, GetMediaExceptionByMediaKeyByMediaKeyErrors, GetMediaExceptionByMediaKeyByMediaKeyResponses, GetMediaExceptionDefaultValuesData, GetMediaExceptionDefaultValuesErrors, GetMediaExceptionDefaultValuesResponses, PostMediaExceptionData, PostMediaExceptionErrors, PostMediaExceptionResponses, PutMediaExceptionByIdData, PutMediaExceptionByIdErrors, PutMediaExceptionByIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export class PageSpeedOptimizer {
    public static postMediaException<ThrowOnError extends boolean = false>(options: Options<PostMediaExceptionData, ThrowOnError>): RequestResult<PostMediaExceptionResponses, PostMediaExceptionErrors, ThrowOnError> {
        return (options.client ?? client).post<PostMediaExceptionResponses, PostMediaExceptionErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/pagespeed-optimizer/v1/media-exception',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    public static deleteMediaExceptionById<ThrowOnError extends boolean = false>(options: Options<DeleteMediaExceptionByIdData, ThrowOnError>): RequestResult<DeleteMediaExceptionByIdResponses, DeleteMediaExceptionByIdErrors, ThrowOnError> {
        return (options.client ?? client).delete<DeleteMediaExceptionByIdResponses, DeleteMediaExceptionByIdErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/pagespeed-optimizer/v1/media-exception/{id}',
            ...options
        });
    }
    
    public static putMediaExceptionById<ThrowOnError extends boolean = false>(options: Options<PutMediaExceptionByIdData, ThrowOnError>): RequestResult<PutMediaExceptionByIdResponses, PutMediaExceptionByIdErrors, ThrowOnError> {
        return (options.client ?? client).put<PutMediaExceptionByIdResponses, PutMediaExceptionByIdErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/pagespeed-optimizer/v1/media-exception/{id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    public static getMediaExceptionByMediaKeyByMediaKey<ThrowOnError extends boolean = false>(options: Options<GetMediaExceptionByMediaKeyByMediaKeyData, ThrowOnError>): RequestResult<GetMediaExceptionByMediaKeyByMediaKeyResponses, GetMediaExceptionByMediaKeyByMediaKeyErrors, ThrowOnError> {
        return (options.client ?? client).get<GetMediaExceptionByMediaKeyByMediaKeyResponses, GetMediaExceptionByMediaKeyByMediaKeyErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/pagespeed-optimizer/v1/media-exception/by-media-key/{mediaKey}',
            ...options
        });
    }
    
    public static getMediaExceptionDefaultValues<ThrowOnError extends boolean = false>(options?: Options<GetMediaExceptionDefaultValuesData, ThrowOnError>): RequestResult<GetMediaExceptionDefaultValuesResponses, GetMediaExceptionDefaultValuesErrors, ThrowOnError> {
        return (options?.client ?? client).get<GetMediaExceptionDefaultValuesResponses, GetMediaExceptionDefaultValuesErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/pagespeed-optimizer/v1/media-exception/default-values',
            ...options
        });
    }
}
