// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type CreateMediaExceptionRequestModel = {
    mediaKey: string;
    quality: number | string;
    forceWebp: boolean;
};

export type DefaultValuesResponseModel = {
    defaultImageQuality: number | string;
    forceWebP: boolean;
    enabled: boolean;
};

export type MediaExceptionResponseModel = {
    id: string;
    mediaKey: string;
    quality: number | string;
    forceWebp: boolean;
};

export type UpdateMediaExceptionRequestModel = {
    quality: number | string;
    forceWebp: boolean;
};

export type PostMediaExceptionData = {
    body: CreateMediaExceptionRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/pagespeed-optimizer/v1/media-exception';
};

export type PostMediaExceptionErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Conflict
     */
    409: unknown;
};

export type PostMediaExceptionResponses = {
    /**
     * Created
     */
    201: MediaExceptionResponseModel;
};

export type PostMediaExceptionResponse = PostMediaExceptionResponses[keyof PostMediaExceptionResponses];

export type DeleteMediaExceptionByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/pagespeed-optimizer/v1/media-exception/{id}';
};

export type DeleteMediaExceptionByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type DeleteMediaExceptionByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutMediaExceptionByIdData = {
    body: UpdateMediaExceptionRequestModel;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/pagespeed-optimizer/v1/media-exception/{id}';
};

export type PutMediaExceptionByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type PutMediaExceptionByIdResponses = {
    /**
     * OK
     */
    200: MediaExceptionResponseModel;
};

export type PutMediaExceptionByIdResponse = PutMediaExceptionByIdResponses[keyof PutMediaExceptionByIdResponses];

export type GetMediaExceptionByMediaKeyByMediaKeyData = {
    body?: never;
    path: {
        mediaKey: string;
    };
    query?: never;
    url: '/umbraco/pagespeed-optimizer/v1/media-exception/by-media-key/{mediaKey}';
};

export type GetMediaExceptionByMediaKeyByMediaKeyErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type GetMediaExceptionByMediaKeyByMediaKeyResponses = {
    /**
     * OK
     */
    200: MediaExceptionResponseModel;
};

export type GetMediaExceptionByMediaKeyByMediaKeyResponse = GetMediaExceptionByMediaKeyByMediaKeyResponses[keyof GetMediaExceptionByMediaKeyByMediaKeyResponses];

export type GetMediaExceptionDefaultValuesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/pagespeed-optimizer/v1/media-exception/default-values';
};

export type GetMediaExceptionDefaultValuesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type GetMediaExceptionDefaultValuesResponses = {
    /**
     * OK
     */
    200: DefaultValuesResponseModel;
};

export type GetMediaExceptionDefaultValuesResponse = GetMediaExceptionDefaultValuesResponses[keyof GetMediaExceptionDefaultValuesResponses];
