// Copyright (c) Dave Woestenborghs and contributors. Licensed under the MIT License. See LICENSE in the project root for license information.
// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Umbraco.Community.PagespeedOptimizer.Infrastructure.Persistence;

#nullable disable

namespace Umbraco.Community.PagespeedOptimizer.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PageSpeedOptimizerDbContext))]
    partial class PageSpeedOptimizerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("Umbraco.Community.PagespeedOptimizer.Core.Models.MediaException", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("ForceWebp");

                    b.Property<Guid>("MediaKey");

                    b.Property<int>("Quality");

                    b.HasKey("Id");

                    b.ToTable("PageSpeedOptimizer_MediaExceptions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
